# for bringing up the containers in an automagick and organized fashion
# copyright (c) 2018 wildduck.io

version: '2'

services:

  wd_alpha_postgres:
    build: ./postgres/
    container_name: wd_alpha_postgres
    expose:
      - "5432"

  wd_alpha_flask:
    build: ./flask
    container_name: wd_alpha_flask
    ports:
      - "1701:5000"
    volumes:
      - "../server:/opt/server"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=run.py
    depends_on:
      - wd_alpha_postgres
    entrypoint:
      - /wait-for-it.sh
      - postgres:5432
      - --
    command:
      python3 /opt/server/run.py
